---
functional:
  - Пользователь должен иметь возможность искать товары по ключевому слову или категории
  - Пользователь должен иметь возможность фильтровать товары
  - Пользователь должен иметь возможность просматривать товары и просматривать подробную информацию о товаре
  - Пользователь должен иметь возможность добавлять товары в корзину и просматривать содержимое корзины

non-functional:
  - Сайт нужно разработать с учетом удобства использования и оптимизировать для скорости работы
  - Сайт должен быть безопасным и защищать данные пользователя
  - Сайт должен иметь мобильную версию
  - Сайт нужно протестировать на совместимость с последними версиями браузеров
  - Важно, чтобы сайт мог обрабатывать большое количество трафика
  - Сайт должен быть доступен на различных устройствах

implicit:
  - Пользователь должен иметь возможность регистрироваться и создавать аккаунт
  - При регистрации у пользователя запршиваются данные номера телефона или электронная почта
  - При первом посещении, у Пользователя отображается пользовательское соглашение и согласие на обработку персональных данных
  - У пользователя есть возможность оплатить и заказать товар
  - Пользователь должен иметь возможность удалять товары из корзины
  - Пользователь должен иметь возможность менять количество содержимого корзины
  - Пользователь должен иметь возможность перехода со страницы товара на главную
  - Сайт должен быть SPA-приложением
  - Корзина сайта хранится в сессии браузера
